"""
Interactive Terminal CLI for Jesse Coding Bot.
Supports live streaming token output, REPL slash commands, code execution,
and graceful error handling.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

# Ensure source and project root are in sys.path
_ROOT_DIR = Path(__file__).resolve().parent.parent.parent
_SOURCE_DIR = _ROOT_DIR / "source"
for _p in (str(_SOURCE_DIR), str(_ROOT_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

try:
    from bot import JesseCodingBot
    from config import JesseConfig
    from exceptions import (
        JesseAuthenticationError,
        JesseBadRequestError,
        JesseBotError,
        JesseConfigError,
        JesseConnectionError,
        JesseRateLimitError,
        JesseServerError,
        JesseStreamError,
    )
    from executor import ExecutionResult
except ImportError:
    from jesse_coder.bot import JesseCodingBot
    from jesse_coder.config import JesseConfig
    from jesse_coder.exceptions import (
        JesseAuthenticationError,
        JesseBadRequestError,
        JesseBotError,
        JesseConfigError,
        JesseConnectionError,
        JesseRateLimitError,
        JesseServerError,
        JesseStreamError,
    )
    from jesse_coder.executor import ExecutionResult

# ANSI terminal colors
COLOR_RESET = "\033[0m"
COLOR_BOLD = "\033[1m"
COLOR_CYAN = "\033[36m"
COLOR_GREEN = "\033[32m"
COLOR_YELLOW = "\033[33m"
COLOR_RED = "\033[31m"
COLOR_MAGENTA = "\033[35m"
COLOR_GRAY = "\033[90m"


def print_banner(config: JesseConfig, auto_exec: bool = False) -> None:
    """Print welcoming header banner."""
    print(f"{COLOR_CYAN}{COLOR_BOLD}=========================================================={COLOR_RESET}")
    print(f"{COLOR_CYAN}{COLOR_BOLD}            Jesse-Coder (Autonomous Agent)               {COLOR_RESET}")
    print(f"{COLOR_CYAN}{COLOR_BOLD}=========================================================={COLOR_RESET}")
    print(f"{COLOR_GRAY}Model     :{COLOR_RESET} {COLOR_GREEN}{config.model}{COLOR_RESET}")
    print(f"{COLOR_GRAY}Base URL  :{COLOR_RESET} {COLOR_GREEN}{config.base_url}{COLOR_RESET}")
    print(f"{COLOR_GRAY}Auto-Exec :{COLOR_RESET} {COLOR_YELLOW}{'ON' if auto_exec else 'OFF'}{COLOR_RESET} (toggle via /autoexec or use /exec)")
    print(f"{COLOR_GRAY}Commands  :{COLOR_RESET} /help, /exec, /code, /clear, /history, /model <name>, /exit")
    print(f"{COLOR_CYAN}----------------------------------------------------------{COLOR_RESET}\n")


def print_help() -> None:
    """Print available interactive slash commands."""
    print(f"\n{COLOR_YELLOW}{COLOR_BOLD}Available Commands:{COLOR_RESET}")
    print(f"  {COLOR_CYAN}/exec{COLOR_RESET}          - Execute the latest code block generated by Jesse")
    print(f"  {COLOR_CYAN}/code{COLOR_RESET}          - View extracted code block from the latest response")
    print(f"  {COLOR_CYAN}/autoexec{COLOR_RESET}      - Toggle auto-execution mode on/off")
    print(f"  {COLOR_CYAN}/clear{COLOR_RESET}         - Clear conversation history and reset context")
    print(f"  {COLOR_CYAN}/history{COLOR_RESET}       - Print full conversation history")
    print(f"  {COLOR_CYAN}/model <name>{COLOR_RESET}  - Switch model (e.g. /model jesse-prod or jesse-pristine)")
    print(f"  {COLOR_CYAN}/help{COLOR_RESET}          - Show this help message")
    print(f"  {COLOR_CYAN}/exit{COLOR_RESET} or {COLOR_CYAN}/quit{COLOR_RESET} - Exit the chatbot\n")


def display_history(bot: JesseCodingBot) -> None:
    """Print recorded conversation messages."""
    history = bot.get_history()
    print(f"\n{COLOR_YELLOW}{COLOR_BOLD}--- Current Conversation History ({len(history)} messages) ---{COLOR_RESET}")
    for idx, msg in enumerate(history, 1):
        role = msg["role"].upper()
        color = COLOR_MAGENTA if role == "SYSTEM" else (COLOR_GREEN if role == "USER" else COLOR_CYAN)
        preview = msg["content"]
        if len(preview) > 300:
            preview = preview[:300] + " ... [truncated]"
        print(f"{color}[{idx}] {role}:{COLOR_RESET} {preview}")
    print()


def print_execution_result(result: ExecutionResult) -> None:
    """Format and display open-agent style execution output."""
    status_color = COLOR_GREEN if result.is_success else COLOR_RED
    status_text = "SUCCESS" if result.is_success else ("TIMEOUT" if result.timed_out else "FAILED")

    print(f"\n{status_color}{COLOR_BOLD}--- Code Execution Result [{result.language.upper()} - {status_text} (Exit: {result.exit_code}, {result.duration_ms:.1f}ms)] ---{COLOR_RESET}")
    if result.stdout:
        print(f"{COLOR_GREEN}{result.stdout.strip()}{COLOR_RESET}")
    if result.stderr:
        print(f"{COLOR_RED}[STDERR]:\n{result.stderr.strip()}{COLOR_RESET}")
    if result.error and not result.stderr:
        print(f"{COLOR_RED}[ERROR]: {result.error}{COLOR_RESET}")
    if not result.stdout and not result.stderr and not result.error:
        print(f"{COLOR_GRAY}[Process exited with code {result.exit_code} and produced no output]{COLOR_RESET}")
    print(f"{status_color}------------------------------------------------------------{COLOR_RESET}\n")


def run_interactive_cli(bot: Optional[JesseCodingBot] = None, auto_exec: bool = False) -> None:
    """
    Start the interactive chatbot loop with real-time streaming, command processing,
    and open-agent code execution.
    """
    if bot is None:
        try:
            bot = JesseCodingBot()
        except JesseConfigError as ce:
            print(f"{COLOR_RED}Configuration Error:{COLOR_RESET} {ce}")
            sys.exit(1)

    print_banner(bot.config, auto_exec=auto_exec)

    while True:
        try:
            user_input = input(f"{COLOR_GREEN}{COLOR_BOLD}You > {COLOR_RESET}").strip()

            if not user_input:
                continue

            if user_input.startswith("/"):
                parts = user_input.split(maxsplit=1)
                cmd = parts[0].lower()
                arg = parts[1].strip() if len(parts) > 1 else ""

                if cmd in ("/exit", "/quit"):
                    print(f"\n{COLOR_GRAY}Goodbye! Happy coding.{COLOR_RESET}")
                    break

                elif cmd in ("/help", "/?"):
                    print_help()
                    continue

                elif cmd in ("/clear", "/reset"):
                    bot.reset_conversation()
                    print(f"{COLOR_YELLOW}Conversation context cleared.{COLOR_RESET}\n")
                    continue

                elif cmd == "/history":
                    display_history(bot)
                    continue

                elif cmd == "/autoexec":
                    auto_exec = not auto_exec
                    state = "ENABLED" if auto_exec else "DISABLED"
                    print(f"{COLOR_YELLOW}Auto-execution {state}.{COLOR_RESET}\n")
                    continue

                elif cmd in ("/exec", "/run"):
                    if not bot.last_assistant_response:
                        print(f"{COLOR_YELLOW}No previous response available to execute. Ask a question first.{COLOR_RESET}\n")
                        continue

                    block = bot.last_extracted_code
                    if not block:
                        print(f"{COLOR_YELLOW}No executable code found in the last response.{COLOR_RESET}\n")
                        continue

                    print(f"{COLOR_CYAN}Executing {block.language} code...{COLOR_RESET}")
                    result = bot.execute_code(block.code, language=block.language)
                    print_execution_result(result)
                    continue

                elif cmd == "/code":
                    if not bot.last_extracted_code:
                        print(f"{COLOR_YELLOW}No extracted code in current turn.{COLOR_RESET}\n")
                    else:
                        block = bot.last_extracted_code
                        print(f"\n{COLOR_CYAN}{COLOR_BOLD}--- Extracted {block.language.upper()} Code ---{COLOR_RESET}")
                        print(block.code)
                        print(f"{COLOR_CYAN}----------------------------------{COLOR_RESET}\n")
                    continue

                elif cmd == "/model":
                    if not arg:
                        print(f"{COLOR_YELLOW}Current model: {bot.config.model}. Use: /model <name>{COLOR_RESET}\n")
                    else:
                        bot.switch_model(arg)
                        print(f"{COLOR_YELLOW}Switched active model to: {arg}{COLOR_RESET}\n")
                    continue

                else:
                    print(f"{COLOR_RED}Unknown command: {cmd}. Type /help for options.{COLOR_RESET}\n")
                    continue

            # Stream response
            print(f"{COLOR_CYAN}{COLOR_BOLD}Jesse > {COLOR_RESET}", end="", flush=True)

            try:
                for token in bot.ask_stream(user_input):
                    sys.stdout.write(token)
                    sys.stdout.flush()
                print("\n")

                if auto_exec and bot.last_extracted_code:
                    block = bot.last_extracted_code
                    print(f"{COLOR_CYAN}[Auto-executing {block.language} code...]{COLOR_RESET}")
                    result = bot.execute_code(block.code, language=block.language)
                    print_execution_result(result)

            except KeyboardInterrupt:
                print(f"\n{COLOR_YELLOW}[Streaming interrupted by user.]{COLOR_RESET}\n")
                continue

            except JesseAuthenticationError as e:
                print(f"\n{COLOR_RED}[Authentication Error]:{COLOR_RESET} {e}")
                print(f"{COLOR_YELLOW}Tip: Verify your API key.{COLOR_RESET}\n")

            except JesseConnectionError as e:
                print(f"\n{COLOR_RED}[Connection Error]:{COLOR_RESET} {e}")
                print(f"{COLOR_YELLOW}Tip: Ensure network connection and Jesse endpoint reachability.{COLOR_RESET}\n")

            except JesseRateLimitError as e:
                print(f"\n{COLOR_RED}[Rate Limit Exceeded]:{COLOR_RESET} {e}\n")

            except JesseBadRequestError as e:
                print(f"\n{COLOR_RED}[Bad Request]:{COLOR_RESET} {e}\n")

            except JesseServerError as e:
                print(f"\n{COLOR_RED}[Jesse Server Error]:{COLOR_RESET} {e}\n")

            except JesseStreamError as e:
                print(f"\n{COLOR_RED}[Stream Error]:{COLOR_RESET} {e}\n")

            except JesseBotError as e:
                print(f"\n{COLOR_RED}[Jesse Error]:{COLOR_RESET} {e}\n")

            except Exception as e:
                print(f"\n{COLOR_RED}[Unexpected Error]:{COLOR_RESET} {e}\n")

        except (KeyboardInterrupt, EOFError):
            print(f"\n\n{COLOR_GRAY}Session terminated. Goodbye!{COLOR_RESET}")
            break


def run_one_shot(bot: JesseCodingBot, prompt: str, auto_exec: bool = False) -> None:
    """Run a single one-shot prompt with streaming and optional execution."""
    try:
        for token in bot.ask_stream(prompt):
            sys.stdout.write(token)
            sys.stdout.flush()
        print()

        if auto_exec:
            if bot.last_extracted_code:
                block = bot.last_extracted_code
                print(f"\n[Auto-executing generated {block.language} code...]")
                res = bot.execute_code(block.code, language=block.language)
                print_execution_result(res)
            else:
                print("\n[No executable code block found in response.]")

        sys.exit(0)
    except JesseBotError as e:
        print(f"\n[Jesse Error]: {e}", file=sys.stderr)
        sys.exit(2)
    except KeyboardInterrupt:
        print("\n[Interrupted]", file=sys.stderr)
        sys.exit(130)
